--9. Работа с переменными
DECLARE @I1 INT;
SET @I1 = 1;
PRINT @I1;
SELECT @I1;

DECLARE @I2 INT = 2;
PRINT @I2;

PRINT @I1 + @I2

DECLARE @S1 CHAR(20) = '1'
DECLARE @S2 CHAR(20) = '2'
--SELECT '@S1 = '
--      , @S1
PRINT @S1 + @S2

DECLARE @S3 VARCHAR(20) = '1'
DECLARE @S4 VARCHAR(20) = '2'
PRINT @S3 + @S4

DECLARE @D1 DATE = GETDATE()
PRINT @D1
SELECT CONVERT(NVARCHAR(15), @D1, 104) AS [Date as Russian]
      ,CONVERT(NVARCHAR(15), @D1, 102) AS [Other]
      ,CONVERT(NVARCHAR(5), @D1, 104) AS [Short]

DECLARE @M1 MONEY = 10.1
DECLARE @M2 MONEY = 10.1
PRINT NULLIF(@M1, @M2)
PRINT ISNULL(NULLIF(@M1, @M2), 0)

DECLARE @M11 DECIMAL = 10.1
DECLARE @M21 DECIMAL = 10.1
PRINT NULLIF(@M11, @M21)
PRINT ISNULL(NULLIF(@M11, @M21), 0)

DECLARE @CH CHAR(50) = '自行車鏈條。';
PRINT @CH;
DECLARE @VCH VARCHAR(50) = 'qwertyuiop';
PRINT @VCH;
DECLARE @NCH NCHAR(50) = N'自行車鏈條。';
PRINT @NCH;
DECLARE @NVCH NVARCHAR(50) = N'سلسلة للدراجة';
PRINT @NVCH;